---
- hosts: ios
  gather_facts: no
  connection: local
  tasks:
  - name: run show version on ios nodes
    ios_command:
      commands: show version
      provider: "{{cli}}"
    register: output
  - debug: var=output

  